name: meditation
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.7.0
  sqflite: ^2.3.0
  path: ^1.9.0
  audioplayers: ^5.2.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.3
  fl_chart: ^0.65.0
  image_picker: ^1.0.4
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/audio/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/font/HelveticaNeueLight.otf
        - asset: assets/font/HelveticaNeueMedium.otf
          weight: 600
        - asset: assets/font/HelveticaNeueBold.otf
          weight: 700
        - asset: assets/font/HelveticaNeueThin.otf
          weight: 300
